add the get single product API
mdunnio/coinbase-pro pull request #19
Opened 2021-06-14 22:42 UTC by gregwebs

This was tested by using this API in a program. In the usage, a start and end time were given.

2021-06-20 19:47 UTC, mdunnio requested changes

2021-06-20 19:47 UTC, mdunnio commented on src/lib/CoinbasePro/Unauthenticated.hs
> +-- | https://docs.pro.coinbase.com/#get-single-product
Add a newline. Two newlines between function definitions please.

2021-06-20 19:47 UTC, mdunnio commented
One minor comment. Thanks for this!

2021-06-21 00:49 UTC, gregwebs commented
Feel free to edit the PR before or after merging

On Sun, Jun 20, 2021 at 3:47 PM Michael Dunn ***@***.***>
wrote:

> One minor comment. Thanks for this!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mdunnio/coinbase-pro/pull/19#issuecomment-864603109>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAAJHZ2EAL7T2ORJQFONFTTTZAWZANCNFSM46WC3N7A>
> .
>

2021-08-08 16:28 UTC, merged